### ISSUE TITLE
v2 API

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/rusty-xinput#12]
Goals for the V2 API:

* [ ] Make the DLL loading produce a struct that holds the `HMODULE` to the loaded and that unloads the DLL when the struct dropped.
* [ ] All XInput function calls become methods off of the DLL handle. **Effect:** No more fiddling with the atomic loaded tracking values. You can only call a method off of a DLL handle.
* [ ] If a function isn't found in that particular DLL, any calls to it just return that the controller is missing.
* [ ] Eliminate all the `static mut` stuff
* [ ] Provide a "dummy handle" that people can use if there's an error so that they can "call" the functions anyway. so that the rest of the code flow can just pretend that all four controllers are missing (which they effectively are).

**Comment by Lokathor** [comment]
@Arvamer does this sound right?

My design thoughts are related to [the newer version I mentioned](https://github.com/Lokathor/thorium/blob/master/src/bin/win32/xinput.rs). We could still put out the current master as a v1.1 before going to a v2.0

**Comment by Arvamer** [comment]
Overall it sounds good, although I can see one more problem :). At the moment, `XInput` struct is `!Send` and `!Sync` which will cause some problem when someone would like to use it from other thread.

Also, I think that it would be better to return more specific error than `DEVICE_NOT_CONNECTED` if function is not loaded.

**Comment by Lokathor** [comment]
Oh, yeah we can make it `Send` and `Sync`, I just didn't. They're process specific, not thread specific.

And yeah, we can split up the error codes more.

**Comment by Arvamer** [comment]
:+1: 

It's probably still worth releasing current master unless you plan to release 2.0 in a week.

**Comment by Lokathor** [comment]
published as v1.1

**Comment by Lokathor** [comment]
@Arvamer I suppose I should ask before planning too much: since you're my only "customer", if I changed things around to using a DLL handle and making calls off of the handle of a loaded DLL... would you even want to use that design in gilrs? Or does the current "make it global" design suit your needs?

**Comment by Arvamer** [comment]
I would probably switch to using 2.0, but current design is probably good enough for gilrs needs.

**Comment by Lokathor** [comment]
Alright, I'll back burner it, but try to get an improved version out the door eventually.

**Comment by jmgao** [comment]
I've been porting one of my projects from C++ to rust and I needed this functionality so I went ahead and took a stab at it.

(tl;dr: I'm writing an XInput wrapper DLL, so I need to specifically load the system XInput DLL or else I end up infinitely recursing)

**Comment by Lokathor** [comment]
Alright, seems like we got this all fixed up without needing to go all the way to v2 for now.
