### ISSUE TITLE
XInputGetStateEx?

### ISSUE THREAD

**Issue by MaulingMonkey** [Lokathor/rusty-xinput#16]
There's a bunch of hidden xinput functions in later XInput versions - in particular I'm wondering if you'd be interested in a PR to get XInputGetStateEx (ordinal 100) available, which exposes the Guide button on xbox 360 controllers.

http://reverseengineerlog.blogspot.com/2016/06/xinputs-hidden-functions.html

If so, there's also the question of what the behavior should be when the function is missing.  On the one hand, implementing it as just yet another optional function would let the end user detect when it's missing.  On the other hand, you're almost certain to just fall back on regular XInputGetState in those cases...

**Comment by djeedai** [comment]
Note: `XInputGetCapabilitiesEx()` also contains the vendor ID and product ID of the device, which allow deriving a stable gamepad identifier across application restarts. This is missing to allow `gilrs` to implement its `Gamepad::uuid()`, which would allow applications to _e.g._ save per-device user preferences (button mappings, _etc._).

https://gitlab.com/gilrs-project/gilrs/-/issues/153

This StackOverflow answer has some code explaining the fields (I think they're missing from the original link): https://stackoverflow.com/questions/64251320/is-it-possible-to-get-an-xinput-devices-name-product-id-vendor-id-or-some-oth/68879988#68879988

**Comment by Lokathor** [comment]
Can you also link the appropriate MSDN or other docs page for me to reference? I can try to get this all sorted out and released this weekend.

**Comment by djeedai** [comment]
As mentioned in those links, those APIs are unfortunately unofficial/undocumented.

**Comment by Lokathor** [comment]
Ah, okay. That's why I don't have any memory about reading docs for this function ever.

That shouldn't be a problem though, we can still do it.

**Comment by djeedai** [comment]
Awesome, thanks! The StackOverflow link has an example code in C showing the various fields for `XInputGetCapabilitiesEx()`.
