### ISSUE TITLE
linux safe

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/rusty-xinput#2]
We gotta do some conditional compilation work

**Comment by MaulingMonkey** [comment]
What's the intention here - APIs all still exist, but simply error out on linux?
Or the APIs themselves aren't even defined on linux?

**Comment by Lokathor** [comment]
XInput is a winapi interface only.

So we have to either compile to nothing on not-windows, or we have to define a the structs and functions and then act like there's 0 controllers plugged in.

probably the former

**Comment by MaulingMonkey** [comment]
https://github.com/Lokathor/rusty-xinput/blob/b3d6d108842c7e4334a231e0c58e0db789cd349b/src/lib.rs#L28 should already cause the crate to compile to nothing on linux, I have a local change for xinput_demo if you want a PR for that.
