### ISSUE TITLE
We don't support all the way back to 1.24 like CI says we should

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/rusty-xinput#20]
https://ci.appveyor.com/project/Lokathor/rusty-xinput/builds/27101259

But we didn't officially declare a min version I guess? fuzzy.

**Comment by MaulingMonkey** [comment]
Options:
* Limit lazy_static to 1.3.x
* Bump MSRV to 1.27.2 (per [lazy-static.rs#minimum-supported-rustc](https://github.com/rust-lang-nursery/lazy-static.rs#minimum-supported-rustc))
* Do both
