### ISSUE TITLE
Inlining in XInputState

### ISSUE THREAD

**Issue by francesca64** [Lokathor/rusty-xinput#5]
`XInputState` has various trivial methods that just check flags, so would it be a good idea to mark those `#[inline]`?

**Comment by Lokathor** [comment]
I've been told that LLVM will generally inline any single expression function, so I was just letting it do its thing.

I've marked them all inline now, and it's here on github, but not on crates.io. I've got several packages that will get bumps once the 1.27 stuff lands tomorrow, so I'll handle all the publishing stuff then.
