### ISSUE TITLE
Crate may fail to build because of f32::sqrt() is not present in core

### ISSUE THREAD

**Issue by Arvamer** [Lokathor/rusty-xinput#9]
```
   Compiling rusty-xinput v1.1.0 (https://github.com/Lokathor/rusty-xinput#c6e67f8d)
error[E0599]: no method named `sqrt` found for type `f32` in the current scope
   --> C:\Users\Arvamer\.cargo\git\checkouts\rusty-xinput-5babd0003cf82f42\c6e67f8\src/lib.rs:510:74
    |
510 |     let length = (raw_float.0 * raw_float.0 + raw_float.1 * raw_float.1).sqrt();
    |                                                                          ^^^^
```

I have no idea why it sometimes builds, [sqrt is defintly not present in core](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=102f05e7f0fe8bb4e703e497bcf61734) . I got this error when building gilrs-core with rusty-xinput as dependency. Moreover, it builds fine when building gilrs (so dependency graph is gilrs -> gilrs-core -> rusty-xinput).

**Comment by Lokathor** [comment]
Oof, this is a classic one.

So we have three ways to get sqrt that I know of

1) standard lib
2) unstable LLVM intrinsic (nightly)
3) SSE2 hardware call (x86/x86_64, obviously)

It's really weird if this sometimes works and sometimes does not though.

I guess we have to rig up our own sqrt call that dispatches to the right thing? We'd end up requiring that the user compile with some config that matches at least one of the items on that list above.

**Comment by Arvamer** [comment]
There is also [`libm`](https://github.com/rust-lang-nursery/libm) crate.

**Comment by Lokathor** [comment]
Okay that sounds neat too. And i'm sure they'd pick sse2 where available and stuff.

If you want to PR that in I can accept it, or I can try to add it myself later today, but I got stuff to do first.

**Comment by Arvamer** [comment]
What was original motivation for supporting `no_std`? This crate obviously only works on Windows, so standard library is always available.

**Comment by Lokathor** [comment]
At the time it was "just for fun" since you can also use `winapi` in `no_std` mode :P 

I guess now we could take that out as a v2.0.0 change if we wanted to.

Making a wrapper that calls the sse intrinsic is going to cover it for all _practical_ purposes if we go that route. Windows _can_ run on ARM and stuff but it's basically an intel OS
